"""init

Revision ID: 320abc3218b2
Revises: 
Create Date: 2024-05-03 17:44:04.616996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '320abc3218b2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permission',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='rbac'
    )
    op.create_table('role',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('is_super_admin', sa.Boolean(), nullable=False),
    sa.Column('is_everyone', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='rbac'
    )
    op.create_table('role_permission',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permision_id', sa.Integer(), nullable=False),
    sa.Column('write_access', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permision_id'], ['rbac.permission.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['rbac.role.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='rbac'
    )
    op.create_table('role_user',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['rbac.role.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id'),
    schema='rbac'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('role_user', schema='rbac')
    op.drop_table('role_permission', schema='rbac')
    op.drop_table('role', schema='rbac')
    op.drop_table('permission', schema='rbac')
    # ### end Alembic commands ###
