"""correct-spelling-premission

Revision ID: b206925fc09f
Revises: c6d884fb56b3
Create Date: 2024-05-04 17:15:51.091912

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'b206925fc09f'
down_revision = 'c6d884fb56b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role_permission', sa.Column('permission_id', sa.Integer(), nullable=False), schema='rbac')
    op.drop_constraint('role_permission_permision_id_fkey', 'role_permission', schema='rbac', type_='foreignkey')
    op.create_foreign_key(None, 'role_permission', 'permission', ['permission_id'], ['id'], source_schema='rbac', referent_schema='rbac')
    op.drop_column('role_permission', 'permision_id', schema='rbac')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role_permission', sa.Column('permision_id', sa.INTEGER(), autoincrement=False, nullable=False), schema='rbac')
    op.drop_constraint(None, 'role_permission', schema='rbac', type_='foreignkey')
    op.create_foreign_key('role_permission_permision_id_fkey', 'role_permission', 'permission', ['permision_id'], ['id'], source_schema='rbac', referent_schema='rbac')
    op.drop_column('role_permission', 'permission_id', schema='rbac')
    # ### end Alembic commands ###
